# Common
mod_id=atlasviewer
mod_name=AtlasViewer
mod_author=XFactHD
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
java_version=25
mod_version=16.0.2
## MC version used in the common project, see https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.0.5-beta
neoforge_version_range=[26.1.0.1-beta,)

# Gradle
org.gradle.jvmargs=-Xmx3G
