# Common
mod_id=atlasviewer
mod_name=AtlasViewer
mod_author=XFactHD
minecraft_version=1.21.6
minecraft_version_range=[1.21.6, 1.22)
java_version=21
mod_version=13.0.0
## MC version used in the common project, see https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.6-20250617.151856
parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.04.19

# Fabric
fabric_version=0.127.0+1.21.6
fabric_loader_version=0.16.14

# NeoForge
neoforge_version=21.6.0-beta
neoforge_version_range=[21.6.0-beta,)

# Gradle
org.gradle.jvmargs=-Xmx3G
