# Common
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
java_version=25
mod_version=17.0.0
## MC version used in the common project, see https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
asm_version=9.9.1
mixin_version=0.17.0+mixin.0.8.7
mixin_extras_version=0.5.0

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.50-beta
neoforge_version_range=[26.2.0.50-beta,)

# Gradle
org.gradle.jvmargs=-Xmx3G
