modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL v2.1"
issueTrackerURL="https://github.com/XFactHD/AtlasViewer/issues"

[[mods]]
	modId="atlasviewer"
	version="${mod_version}"
	displayName="AtlasViewer"
	#updateJSONURL=""
	#displayURL=""
	logoFile="logo.png"
	#credits="Thanks for this example mod goes to Java"
	authors="XFactHD"
	description='''
	'''

[[dependencies.atlasviewer]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.atlasviewer]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
