plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version

    validateAccessTransformers = true

    accessTransformers = ['src/main/resources/META-INF/accesstransformer.cfg']
    interfaceInjectionData = files('src/main/resources/interfaces.json')
}

dependencies {
    compileOnly("net.fabricmc:sponge-mixin:${mixin_version}")

    compileOnly("io.github.llamalad7:mixinextras-common:${mixin_extras_version}")
    annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}")

    // Required to make the mixin AP happy when hotswapping with SingleHotswap (IDEA does stupid stuff with the processorpath)
    compileOnly("org.ow2.asm:asm:${asm_version}")
    compileOnly("org.ow2.asm:asm-analysis:${asm_version}")
    compileOnly("org.ow2.asm:asm-commons:${asm_version}")
    compileOnly("org.ow2.asm:asm-tree:${asm_version}")
    compileOnly("org.ow2.asm:asm-util:${asm_version}")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
