plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    validateAccessTransformers = true

    accessTransformers = ['../common/src/main/resources/META-INF/accesstransformer.cfg']
    interfaceInjectionData = files('../common/src/main/resources/interfaces.json')

    runs {
        configureEach {
            systemProperty('terminal.ansi', 'true')
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            gameDirectory = project.file('run_client')
        }

        server {
            server()
            gameDirectory = project.file('run_server')
            programArgument '--nogui'
        }
    }

    mods {
        atlasviewer {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
